trigger:

- master

resources:
- repo: self

variables:
- name: tag
  value: '$(Build.BuildId)'
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CmdLine@2
      displayName: 'Login to AWS'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      inputs:
        script: aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
    - task: Docker@2
      displayName: Build docker image
      inputs:
        repository: $(DOCKER_REPOSITORY)
        command: buildAndPush
        Dockerfile: amcombootcamp-aws-lambda-trigger/Dockerfile        
        tags: |-
          latest
    
    - task: GitHubRelease@1
      inputs:
        gitHubConnection: 'marcoslobo'
        repositoryName: 'marcoslobo/amcombootcamp-aws-lambda-trigger'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'gitTag'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'
 

